name: Continuous Integration (Xcode)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: "Import Certificate: Development"
      uses: devbotsxyz/import-signing-certificate@main
      with:
        certificate-data: ${{ secrets.DEVELOPMENT_CERTIFICATE_DATA }}
        certificate-passphrase: ${{ secrets.DEVELOPMENT_CERTIFICATE_PASSPHRASE }}
        keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}
    
    - name: Xcode Build
      uses: devbotsxyz/xcode-build@v1.0.0
      with:
        #workspace: "$GITHUB_WORKSPACE/ReMousr"
        project: "Xcode/ReMousr/ReMousr.xcodeproj"
        scheme: "ReMousr"
        configuration: "Debug,Release"
        # Code sign identity
        #code-sign-identity: # optional, default is -
